language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - 'nightly'

env:
  global:
    - OCULAR_BIN=$HOME/.bin/ocular.phar

branches:
    only:
        - master
        - 1.x

matrix:
  fast_finish: true
  include:
    - php: '5.6'
      env:
        - SYMFONY_VERSION="~2.7.0"
        - COMPOSER_FLAGS="--prefer-lowest"
        - COVERAGE_ENABLED="true"
        - PHPUNIT_FLAGS="--coverage-text --coverage-clover=coverage.xml"
    - php: '7.0'
      env:
        - SYMFONY_VERSION="~2.7.0"
        - COMPOSER_FLAGS="--prefer-lowest"
        - COVERAGE_ENABLED="true"
        - PHPUNIT_FLAGS="--coverage-text --coverage-clover=coverage.xml"
    - php: '7.1'
      env: SYMFONY_VERSION="~2.7.0"
    - php: '7.1'
      env: SYMFONY_VERSION="~2.8.0"
    - php: '7.1'
      env: SYMFONY_VERSION="~3.1.0"
    - php: '7.1'
      env: 
        - SYMFONY_VERSION="~3.2.0"
        - COVERAGE_ENABLED="true"
        - PHPUNIT_FLAGS="--coverage-text --coverage-clover=coverage.xml"
    - php: '7.1'
      env: SYMFONY_VERSION="~3.3.0@dev"
    - php: 'nightly'
      env: SYMFONY_VERSION="~3.2.0"
  allow_failures:
    - env: SYMFONY_VERSION="~3.3.0@dev"
    - php: 'nightly'

services:
  - mongodb
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.bin/

before_install:
  - |
    if [ -z "$COVERAGE_ENABLED" ]; then
      (php --ini | grep xdebug) && phpenv config-rm xdebug.ini
    fi
  - |
    if [ "$SYMFONY_VERSION" != "" ]; then
      composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update
    fi
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - |
    if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then
      echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    else
      echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    fi
  - |
    if [ -n "$COVERAGE_ENABLED" ] && [ ! -e $OCULAR_BIN ]; then
      wget https://scrutinizer-ci.com/ocular.phar -O $OCULAR_BIN
      alias ocular="php $OCULAR_BIN"
    fi

install:
  - composer update --prefer-dist --no-interaction --ignore-platform-reqs $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit --stop-on-failure --verbose $PHPUNIT_FLAGS

after_script:
  - |
    if [ -n "$COVERAGE_ENABLED" ]; then
      ocular code-coverage:upload --format=php-clover coverage.xml
    fi

notifications:
  email: false
